[project]
name = "tcd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "skrebate>=0.62",
]
